# stack name: main

version: '3.7'

networks:

  default:
    # 不写这个的话只有 docker service 的容器才可以使用这个网络, 这样的话手动运行单个容器进行调试时会很麻烦
    attachable: true

  # 与其他 docker service stack 互通的网络
  link:
    attachable: true

  # 这个是继承的本机网络, 是最快的docker网络. 因为不追求极限性能, 所以这里不会使用到它, 只是分享下我的经验, 为后期优化提供思路.
  # 它的缺点: 会端口冲突, 不能与其他overlay网络(指上面的两个网络)互通
  xhost:
    external: true
    name: host

services:

  proxy:
    image: caddy:2.3.0@sha256:8fda56a5fc2e3f7ec352fe576c270a864249dd2c11033ffaa1251603b2c3ee9a
    networks: [ 'default', 'link' ]
    ports:
      # 这种写法可以获取来源 ip, 但限制是只能有一个这样的容器启动不然会端口冲突, 所以下面的 stop-frist 是必要的
      - { mode: host, protocol: tcp, target: 80, published: 80 }
      - { mode: host, protocol: tcp, target: 443, published: 443 }
    volumes:
      - /work/caddy:/etc/caddy/:rslave
    logging: &logging
      options: { max-size: "200k", max-file: "10" }
    deploy:  &deploy
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy: { condition: on-failure, max_attempts: 3 }
      update_config: { parallelism: 0, failure_action: rollback, max_failure_ratio: 1, order: stop-first }
